"""
Real battery degradation data — NASA PCoE Li-ion Aging Dataset.

This is the ground truth the degradation model is validated against. Fitting a
model to synthetic data generated by a process we wrote ourselves proves
nothing; these are four 18650 cells cycled to failure in a lab, with measured
capacity fade and ground-truth remaining-useful-life labels.

See data/nasa/SOURCE.md for provenance and for which cells were excluded.
"""

import os
from functools import lru_cache
from typing import Dict, List, Optional

import numpy as np
import pandas as pd

DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "nasa")

# Cells are 18650s rated 2.0 Ah nominal.
RATED_CAPACITY_AH = 2.0

# Automotive traction end-of-life, consistent with the rest of the platform.
EOL_SOH_PCT = 70.0

BENCHMARK_CELLS = ["B0005", "B0006", "B0007", "B0018"]


@lru_cache(maxsize=1)
def load_cells() -> Dict[str, pd.DataFrame]:
    """Load and validate the benchmark cells. Cached — files never change."""
    cells: Dict[str, pd.DataFrame] = {}
    for cell in BENCHMARK_CELLS:
        path = os.path.join(DATA_DIR, f"{cell}.csv")
        if not os.path.exists(path):
            continue
        df = pd.read_csv(path)
        if "capacity" not in df.columns:
            continue

        df = df.reset_index(drop=True)
        df["cycle"] = df.index + 1
        df["soh_pct"] = df["capacity"] / RATED_CAPACITY_AH * 100.0

        # Reject anything that is not a degradation curve — see SOURCE.md.
        if df["soh_pct"].iloc[-1] >= df["soh_pct"].iloc[0]:
            continue
        cells[cell] = df
    return cells


def available_cells() -> List[str]:
    return sorted(load_cells().keys())


def cell_summary() -> List[Dict]:
    """Headline facts per cell, for display."""
    out = []
    for cell, df in sorted(load_cells().items()):
        out.append({
            "cell": cell,
            "cycles": int(len(df)),
            "initial_capacity_ah": round(float(df["capacity"].iloc[0]), 3),
            "final_capacity_ah": round(float(df["capacity"].iloc[-1]), 3),
            "initial_soh_pct": round(float(df["soh_pct"].iloc[0]), 1),
            "final_soh_pct": round(float(df["soh_pct"].iloc[-1]), 1),
            "total_fade_pct": round(
                float(100 * (1 - df["capacity"].iloc[-1] / df["capacity"].iloc[0])), 1
            ),
            "mean_discharge_temp_c": round(float(df["max_temp_D"].mean()), 1),
        })
    return out


def cell_curve(cell: str) -> Optional[Dict]:
    """Measured SoH-vs-cycle curve for one cell."""
    df = load_cells().get(cell)
    if df is None:
        return None
    return {
        "cell": cell,
        "rated_capacity_ah": RATED_CAPACITY_AH,
        "points": [
            {
                "cycle": int(r["cycle"]),
                "capacity_ah": round(float(r["capacity"]), 4),
                "soh_pct": round(float(r["soh_pct"]), 2),
                "remaining_cycles": (
                    int(r["remaining_cycles"]) if "remaining_cycles" in df.columns else None
                ),
                "max_temp_c": round(float(r["max_temp_D"]), 1),
            }
            for _, r in df.iterrows()
        ],
    }
